### ISSUE TITLE
The master not work in boot2docker.

### ISSUE THREAD

**Issue by piaolinzhi** [cagdascirit/docker-jmeter#1]
Hi, I want to use jmeter for performance test on my project and I find you images.
But the master container created did not work in the boot2docker env. 
I started the container as the document description.

The dokcer log as follows 

docker@default:~$ docker logs slave1
Using local port: 60000
Created remote object: UnicastServerRef [liveRef: [endpoint:[172.17.0.2:60000](local),objID:[55f9f24f:1521ef97350:-7fff, -5941856432947821918]]]

docker@default:~$ docker logs master
Jan 08, 2016 3:18:06 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.

Any help will be appreciated. Thanks a lot.

**Comment by cagdascirit** [comment]
Hi @piaolinzhi I just tried master and slaves on my machine by using DockerToolbox-1.9.1g and everything is working correctly.

My docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Please specify your OS info, docker version, docker toolbox version (boot2docker is deprecated?) and container parameters that you are passing for the further investigation..

**Comment by piaolinzhi** [comment]
Thanks for replying.
I install DockerToolbox-1.9.1f on a thinkpad notebook with win10OS installed. The images used was pulled from docker official reg repository. 
My docker info is 
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 167
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: RX63:MDJC:AYXH:QP2H:UGE6:7F35:VJMT:NRRF:CZXQ:BUKW:EBP7:WNT7
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2016-01-11T09:29:49.820757884Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by cagdascirit** [comment]
@piaolinzhi and please specify your slave and master container parameters that you are passing when you are starting the containers..
